baseURL = "https://saorsadev.com"
languageCode = "en-us"
title = "SaorsaDev"
theme = "ananke"

[params]
  noindex = false
  nofollow = false

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  page = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["html"]

[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    baseName = "index"
